// src/components/providers/ThemeProvider.tsx
"use client";
import React, { ReactNode, useContext, useState } from "react";

interface ThemeSettings {
  heroColors: {
    text: string;
    background: string;
  }
  setHeroColors?: React.Dispatch<React.SetStateAction<ThemeSettings['heroColors']>>,
}

const defaultThemeSettings: ThemeSettings = {
  heroColors: {
    text: '#ffffff',
    background: '#000000'
  },
};

const ThemeContext = React.createContext(defaultThemeSettings);
export const useThemeContext = () => useContext(ThemeContext);

export default function ThemeProvider({ children }: { children: ReactNode }) {
  const [heroColors, setHeroColors] = useState<ThemeSettings['heroColors']>(defaultThemeSettings.heroColors);

  return <ThemeContext.Provider value={{
    heroColors,
    setHeroColors,
  }}>
    {children}
  </ThemeContext.Provider>
}

// src/components/providers/ThemeProvider.vue
<script lang="ts">
import { ref, provide, inject, Ref } from 'vue';

export interface ThemeColors {
  text: string;
  background: string;
}

export interface ThemeContextType {
  heroColors: Ref<ThemeColors>;
  setHeroColors: (colors: ThemeColors) => void;
}

export function useThemeContext() {
  const context = inject<ThemeContextType>('themeContext');
  if (!context) {
    return {
      heroColors: ref({ text: '#ffffff', background: '#000000' }),
      setHeroColors: () => {}
    };
  }
  return context;
}
</script>

<script setup lang="ts">
const heroColors = ref<ThemeColors>({
  text: '#ffffff',
  background: '#000000'
});

const setHeroColors = (colors: ThemeColors) => {
  heroColors.value = colors;
};

provide('themeContext', {
  heroColors,
  setHeroColors
});
</script>

<template>
  <slot />
</template>
