// src/components/sections/CareerItem/index.tsx
import React from "react";
import styles from "./styles.module.scss";
import LocationPin from "@/assets/icons/LocationPin";
import MoneyCheck from "@/assets/icons/MoneyCheck";

interface CareerItemProps {
  title: string,
  description: string,
  contestlink: string,
  website: string,
  mailadress: string,
  websiteLink: string,
  mailadressLink: string,
}

export default function CareerItem({ title, description, contestlink, website, mailadress, websiteLink, mailadressLink }: CareerItemProps) {
  return <div className={styles.outer}>
    <div className={styles.inner}>
      <div className={styles.title}>
        {title}
      </div>
      <div className={styles.description}>
        {description}
      </div>
      <div className={styles.controls}>
        <div className={styles.btn}>
          <a href={contestlink} className={styles.contest}>Check out the project</a>
        </div>
      </div>
      <div className={styles.meta}>
        <div className={styles.salary}>
          <MoneyCheck /> <a href={mailadressLink} className={styles.contesttime}>{mailadress}</a>
        </div>
        <div className={styles.location}>
          <LocationPin /> <a href={websiteLink} className={styles.contesttime}>{website}</a>
        </div>
      </div>
      <div className={styles.positionHaunted}>
        {title.split('(')[0].trim()}
      </div>
    </div>
  </div>
}

// src/components/sections/CareerItem.vue
<script setup lang="ts">
import styles from './CareerItem/styles.module.scss';
import LocationPin from '@/components/icons/LocationPin.vue';
import MoneyCheck from '@/components/icons/MoneyCheck.vue';

const props = defineProps<{
  title: string;
  description: string;
  contestlink: string;
  website: string;
  mailadress: string;
  websiteLink: string;
  mailadressLink: string;
}>();
</script>

<template>
  <div :class="styles.outer">
    <div :class="styles.inner">
      <div :class="styles.title">
        {{ props.title }}
      </div>
      <div :class="styles.description">
        {{ props.description }}
      </div>
      <div :class="styles.controls">
        <div :class="styles.btn">
          <a :href="props.contestlink" :class="styles.contest">Check out the project</a>
        </div>
      </div>
      <div :class="styles.meta">
        <div :class="styles.salary">
          <MoneyCheck />
          <a :href="props.mailadressLink" :class="styles.contesttime">{{ props.mailadress }}</a>
        </div>
        <div :class="styles.location">
          <LocationPin />
          <a :href="props.websiteLink" :class="styles.contesttime">{{ props.website }}</a>
        </div>
      </div>
      <div :class="styles.positionHaunted">
        {{ props.title.split('(')[0].trim() }}
      </div>
    </div>
  </div>
</template>
