// src/components/sections/Story.tsx
import React, { useEffect, useRef, useState } from "react";
import styles from "./sections.module.scss";
import SectionTitle from "@/components/shared/SectionTitle";
import StoryCarousel from "@/components/carousels/StoryCarousel";
import Story01 from "@/assets/figures/story-1.png";
import Story02 from "@/assets/figures/8idet6.png";
import ScrollReveal from "@/components/utils/ScrollReveal";
import { useLanguage } from "@/components/providers/LanguageProvider";



export default function Story() {
  const [activated, setActivated] = useState(false);
  const [index, setIndex] = useState(0);
  const outerRef = useRef<HTMLDivElement>(null);
  const { t } = useLanguage();

  useEffect(() => {
    window.addEventListener('scroll', e => {
      if (outerRef.current?.offsetTop && outerRef.current?.offsetTop - window.scrollY < 300) {
        setActivated(true);
      }
    });
  }, []);

  const Slides = [
    {
      image: Story01.src,
      date: t.story.slides.slide1.date,
      title: <>
        <h3 dangerouslySetInnerHTML={{ __html: t.story.slides.slide1.title }} />
        <span>{t.story.slides.slide1.subtitle}</span>
      </>,
      content: <>
        <p dangerouslySetInnerHTML={{ __html: t.story.slides.slide1.p1 }} />
        <p dangerouslySetInnerHTML={{ __html: t.story.slides.slide1.p2 }} />
      </>
    },
    {
      image: Story02.src,
      date: t.story.slides.slide2.date,
      title: <>
        <h3 dangerouslySetInnerHTML={{ __html: t.story.slides.slide2.title }} />
        <span>{t.story.slides.slide2.subtitle}</span>
      </>,
      content: <>
        <p dangerouslySetInnerHTML={{ __html: t.story.slides.slide2.p1 }} />
        <p dangerouslySetInnerHTML={{ __html: t.story.slides.slide2.p2 }} />
        <p dangerouslySetInnerHTML={{ __html: t.story.slides.slide2.p3 }} />
      </>
    }
  ];

  return <div
    ref={outerRef}
    id={'story'}
    className={styles.section}
  >
    <div className={styles.sectionContent}>
      <ScrollReveal>
        <SectionTitle>
          {t.story.title}
        </SectionTitle>
        <div>
          {t.story.subtitle}
        </div>

        <StoryCarousel
          slides={Slides}
          index={index}
          date={Slides[index].date}
          activated={activated} image={Slides[index].image}
          onNext={() => setIndex(i => i + 1)}
          onPrev={() => setIndex(i => i - 1)}
          canGoNext={index < Slides.length - 1}
          canGoPrev={index > 0}
        />
        {activated && (
          <div className={styles.storyText} key={index}>
            <div className={`${styles.storyTextContent}`}>
              {Slides[index].content}
            </div>
            <div className={`${styles.storyTextTitle}`}>
              {Slides[index].title}
            </div>
          </div>
        )}
      </ScrollReveal>
    </div>
  </div>
}

// src/components/sections/Story.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, computed } from 'vue';
import styles from './sections.module.scss';
import SectionTitle from '@/components/shared/SectionTitle.vue';
import StoryCarousel from '@/components/carousels/StoryCarousel/index.vue';
import Story01 from '@/assets/figures/story-1.png';
import Story02 from '@/assets/figures/8idet6.png';
import ScrollReveal from '@/components/utils/ScrollReveal.vue';
import { useLanguage } from '@/components/providers/LanguageProvider.vue';

const activated = ref(false);
const index = ref(0);
const outerRef = ref<HTMLDivElement | null>(null);
const { t } = useLanguage();

const handleScroll = () => {
  if (outerRef.value?.offsetTop && outerRef.value.offsetTop - window.scrollY < 300) {
    activated.value = true;
  }
};

onMounted(() => {
  window.addEventListener('scroll', handleScroll);
  handleScroll(); // Trigger check initially
});

onUnmounted(() => {
  window.removeEventListener('scroll', handleScroll);
});

const slides = computed(() => [
  {
    image: Story01,
    date: t.value.story.slides.slide1.date,
    titleHtml: `<h3>${t.value.story.slides.slide1.title}</h3><span>${t.value.story.slides.slide1.subtitle}</span>`,
    contentHtml: `<p>${t.value.story.slides.slide1.p1}</p><p>${t.value.story.slides.slide1.p2}</p>`
  },
  {
    image: Story02,
    date: t.value.story.slides.slide2.date,
    titleHtml: `<h3>${t.value.story.slides.slide2.title}</h3><span>${t.value.story.slides.slide2.subtitle}</span>`,
    contentHtml: `<p>${t.value.story.slides.slide2.p1}</p><p>${t.value.story.slides.slide2.p2}</p><p>${t.value.story.slides.slide2.p3}</p>`
  }
]);

const nextSlide = () => {
  if (index.value < slides.value.length - 1) {
    index.value++;
  }
};

const prevSlide = () => {
  if (index.value > 0) {
    index.value--;
  }
};
</script>

<template>
  <div
    ref="outerRef"
    id="story"
    :class="styles.section"
  >
    <div :class="styles.sectionContent">
      <ScrollReveal>
        <SectionTitle>{{ t.story.title }}</SectionTitle>
        <div>
          {{ t.story.subtitle }}
        </div>

        <StoryCarousel
          :slides="slides"
          :index="index"
          :date="slides[index].date"
          :activated="activated"
          :image="slides[index].image"
          :canGoNext="index < slides.length - 1"
          :canGoPrev="index > 0"
          @next="nextSlide"
          @prev="prevSlide"
        />

        <div v-if="activated" :class="styles.storyText" :key="index">
          <div :class="styles.storyTextContent" v-html="slides[index].contentHtml" />
          <div :class="styles.storyTextTitle" v-html="slides[index].titleHtml" />
        </div>
      </ScrollReveal>
    </div>
  </div>
</template>
