// src/components/sections/Team.vue
<script setup lang="ts">
import styles from './styles.module.scss';
import SectionTitle from '@/components/shared/SectionTitle.vue';
import ProfileCard from '@/components/ProfileCard.vue';
import ScrollReveal from '@/components/utils/ScrollReveal.vue';

const members = [
  {
    name: "Alyosha",
    title: "Team Leader & Software Engineer",
    handle: "ssdarealest",
    avatarUrl: "https://cdn.imgchest.com/files/522ca93545bf.jpg",
    miniAvatarUrl: "https://cdn.imgchest.com/files/37d75fe91a04.jpg",
    website: "https://akk1to.tech",
    status: "the state of mind."
  },
  {
    name: "Heiznerd",
    title: "Frontend Developer",
    handle: "captainnhwuy",
    avatarUrl: "https://cdn.imgchest.com/files/ffceb2c2933a.png",
    miniAvatarUrl: "https://cdn.imgchest.com/files/3bbfb29ac0b3.jpg",
    website: "https://heiznerd.is-a.dev/",
    status: "! heiznerd."
  },
  {
    name: "maiminhdung",
    title: "Backend & Mobile Developer",
    handle: "maiminhdung",
    avatarUrl: "https://cdn.imgchest.com/files/aa2db9376aa7.jpg",
    miniAvatarUrl: "https://cdn.imgchest.com/files/ff3602e5b701.gif",
    website: "https://maiminhdung.dev/",
    status: "Mai Minh Dung"
  }
];

const handleContactClick = (url: string) => {
  window.location.href = url;
};
</script>

<template>
  <div id="team" :class="styles.teamSection">
    <ScrollReveal :className="styles.header">
      <SectionTitle>Our Team</SectionTitle>
      <div :class="styles.subtitle">
        Meet our amazing team...
      </div>
    </ScrollReveal>

    <ScrollReveal :delay="0.2" :className="styles.grid">
      <ProfileCard
        v-for="(member, index) in members"
        :key="index"
        :name="member.name"
        :title="member.title"
        :handle="member.handle"
        :status="member.status"
        contactText="Contact Me"
        :avatarUrl="member.avatarUrl"
        :miniAvatarUrl="member.miniAvatarUrl"
        :showUserInfo="true"
        :enableTilt="false"
        :enableMobileTilt="false"
        :behindGlowEnabled="false"
        :showShine="false"
        @contactClick="() => handleContactClick(member.website)"
        behindGlowColor="rgba(0,0,0,0)"
        behindGlowSize="0%"
        innerGradient="none"
      />
    </ScrollReveal>
  </div>
</template>

// src/app/team/page.tsx
"use client";
import React from "react";
// @ts-ignore
import ProfileCard from "@/components/ProfileCard";
import styles from "@/components/sections/styles.module.scss";

interface TeamMember {
  name: string;
  title: string;
  handle: string;
  avatarUrl: string;
}

const teamMembers: TeamMember[] = [
  {
    name: "Javi A. Torres",
    title: "Software Engineer",
    handle: "javicodes",
    avatarUrl: "https://placehold.co/300x600",
  },
  {
    name: "Member 2",
    title: "Software Engineer",
    handle: "mem2",
    avatarUrl: "https://placehold.co/300x600",
  },
  {
    name: "Member 3",
    title: "Software Engineer",
    handle: "mem3",
    avatarUrl: "https://placehold.co/300x600",
  },
  {
    name: "Member 4",
    title: "Software Engineer",
    handle: "mem4",
    avatarUrl: "https://placehold.co/300x600",
  },
  {
    name: "Member 5",
    title: "Software Engineer",
    handle: "mem5",
    avatarUrl: "https://placehold.co/300x600",
  },
  {
    name: "Member 6",
    title: "Software Engineer",
    handle: "mem6",
    avatarUrl: "https://placehold.co/300x600",
  },
];

export default function TeamPage() {
  return (
    <div className={styles.teamSection}>
      <div className={styles.header}>
        <h2 className={styles.title}>Our team</h2>
        <p className={styles.subtitle}>Meet the minds behind the magic</p>
      </div>
      <div className={styles.grid}>
        {teamMembers.map((member, index) => (
          <ProfileCard
            key={index}
            name={member.name}
            title={member.title}
            handle={member.handle}
            status="Online"
            contactText="Contact Me"
            avatarUrl={member.avatarUrl}
            showUserInfo={true}
            enableTilt={true}
            enableMobileTilt={false}
            onContactClick={() => window.location.href = "https://example.com"}
            miniAvatarUrl={null}
            behindGlowEnabled={false}
            behindGlowColor="rgba(0,0,0,0)"
            behindGlowSize={0}
            showShine={false}
            innerGradient="none"
          />
        ))}
      </div>
    </div>
  );
}
